# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(870, 660)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(870, 660))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.main_vertical_layout = QtWidgets.QVBoxLayout()
        self.main_vertical_layout.setObjectName("main_vertical_layout")
        self.genVisualization = PlotWidget(self.centralwidget)
        self.genVisualization.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.genVisualization.sizePolicy().hasHeightForWidth())
        self.genVisualization.setSizePolicy(sizePolicy)
        self.genVisualization.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.genVisualization.setInteractive(False)
        self.genVisualization.setObjectName("genVisualization")
        self.main_vertical_layout.addWidget(self.genVisualization)
        self.curChrLabelGrid = QtWidgets.QGridLayout()
        self.curChrLabelGrid.setObjectName("curChrLabelGrid")
        self.gen_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gen_label.sizePolicy().hasHeightForWidth())
        self.gen_label.setSizePolicy(sizePolicy)
        self.gen_label.setObjectName("gen_label")
        self.curChrLabelGrid.addWidget(self.gen_label, 2, 0, 1, 1)
        self.gen_value_box = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gen_value_box.sizePolicy().hasHeightForWidth())
        self.gen_value_box.setSizePolicy(sizePolicy)
        self.gen_value_box.setObjectName("gen_value_box")
        self.curChrLabelGrid.addWidget(self.gen_value_box, 2, 5, 1, 1)
        self.mingen_label = QtWidgets.QLabel(self.centralwidget)
        self.mingen_label.setObjectName("mingen_label")
        self.curChrLabelGrid.addWidget(self.mingen_label, 3, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.prog_start_btn = QtWidgets.QPushButton(self.centralwidget)
        self.prog_start_btn.setObjectName("prog_start_btn")
        self.horizontalLayout.addWidget(self.prog_start_btn)
        self.prog_stop_btn = QtWidgets.QPushButton(self.centralwidget)
        self.prog_stop_btn.setObjectName("prog_stop_btn")
        self.horizontalLayout.addWidget(self.prog_stop_btn)
        self.curChrLabelGrid.addLayout(self.horizontalLayout, 3, 5, 1, 1)
        self.maxgen_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxgen_label.sizePolicy().hasHeightForWidth())
        self.maxgen_label.setSizePolicy(sizePolicy)
        self.maxgen_label.setObjectName("maxgen_label")
        self.curChrLabelGrid.addWidget(self.maxgen_label, 2, 1, 1, 1)
        self.lastgen_label = QtWidgets.QLabel(self.centralwidget)
        self.lastgen_label.setObjectName("lastgen_label")
        self.curChrLabelGrid.addWidget(self.lastgen_label, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.curChrLabelGrid.addItem(spacerItem, 3, 2, 1, 1)
        self.gencount_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gencount_label.sizePolicy().hasHeightForWidth())
        self.gencount_label.setSizePolicy(sizePolicy)
        self.gencount_label.setObjectName("gencount_label")
        self.curChrLabelGrid.addWidget(self.gencount_label, 2, 2, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.curChrLabelGrid.addWidget(self.progressBar, 2, 3, 1, 1)
        self.prog_save_btn = QtWidgets.QPushButton(self.centralwidget)
        self.prog_save_btn.setObjectName("prog_save_btn")
        self.curChrLabelGrid.addWidget(self.prog_save_btn, 3, 3, 1, 1)
        self.main_vertical_layout.addLayout(self.curChrLabelGrid)
        self.key_layout = QtWidgets.QGridLayout()
        self.key_layout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.key_layout.setObjectName("key_layout")
        self.row1 = QtWidgets.QHBoxLayout()
        self.row1.setObjectName("row1")
        spacerItem1 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.row1.addItem(spacerItem1)
        self.key12 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key12.sizePolicy().hasHeightForWidth())
        self.key12.setSizePolicy(sizePolicy)
        self.key12.setStyleSheet("color: black;\n"
"background-color: rgb(204, 204, 204);\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"width: 54px;\n"
"height: 54px;\n"
"outline:none\n"
"")
        self.key12.setObjectName("key12")
        self.row1.addWidget(self.key12)
        self.key13 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key13.sizePolicy().hasHeightForWidth())
        self.key13.setSizePolicy(sizePolicy)
        self.key13.setStyleSheet("color: black;\n"
"background-color: rgb(204, 204, 204);\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"width: 54px;\n"
"height: 54px;\n"
"outline:none\n"
"")
        self.key13.setObjectName("key13")
        self.row1.addWidget(self.key13)
        self.key14 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key14.sizePolicy().hasHeightForWidth())
        self.key14.setSizePolicy(sizePolicy)
        self.key14.setStyleSheet("color: black;\n"
"background-color: rgb(204, 204, 204);\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"width: 54px;\n"
"height: 54px;\n"
"outline:none\n"
"")
        self.key14.setObjectName("key14")
        self.row1.addWidget(self.key14)
        self.key15 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key15.sizePolicy().hasHeightForWidth())
        self.key15.setSizePolicy(sizePolicy)
        self.key15.setStyleSheet("color: black;\n"
"background-color: rgb(204, 204, 204);\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"width: 54px;\n"
"height: 54px;\n"
"outline:none\n"
"")
        self.key15.setObjectName("key15")
        self.row1.addWidget(self.key15)
        self.key16 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key16.sizePolicy().hasHeightForWidth())
        self.key16.setSizePolicy(sizePolicy)
        self.key16.setStyleSheet("color: black;\n"
"background-color: rgb(204, 204, 204);\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"width: 54px;\n"
"height: 54px;\n"
"outline:none\n"
"")
        self.key16.setObjectName("key16")
        self.row1.addWidget(self.key16)
        self.key17 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key17.sizePolicy().hasHeightForWidth())
        self.key17.setSizePolicy(sizePolicy)
        self.key17.setStyleSheet("color: black;\n"
"background-color: rgb(204, 204, 204);\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"width: 54px;\n"
"height: 54px;\n"
"outline:none\n"
"")
        self.key17.setObjectName("key17")
        self.row1.addWidget(self.key17)
        self.key18 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key18.sizePolicy().hasHeightForWidth())
        self.key18.setSizePolicy(sizePolicy)
        self.key18.setStyleSheet("color: black;\n"
"background-color: rgb(204, 204, 204);\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"width: 54px;\n"
"height: 54px;\n"
"outline:none\n"
"")
        self.key18.setObjectName("key18")
        self.row1.addWidget(self.key18)
        self.key19 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key19.sizePolicy().hasHeightForWidth())
        self.key19.setSizePolicy(sizePolicy)
        self.key19.setStyleSheet("color: black;\n"
"background-color: rgb(204, 204, 204);\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"width: 54px;\n"
"height: 54px;\n"
"outline:none\n"
"")
        self.key19.setObjectName("key19")
        self.row1.addWidget(self.key19)
        self.key20 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key20.sizePolicy().hasHeightForWidth())
        self.key20.setSizePolicy(sizePolicy)
        self.key20.setStyleSheet("color: black;\n"
"background-color: rgb(204, 204, 204);\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"width: 54px;\n"
"height: 54px;\n"
"outline:none\n"
"")
        self.key20.setObjectName("key20")
        self.row1.addWidget(self.key20)
        self.key21 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key21.sizePolicy().hasHeightForWidth())
        self.key21.setSizePolicy(sizePolicy)
        self.key21.setStyleSheet("color: black;\n"
"background-color: rgb(204, 204, 204);\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"width: 54px;\n"
"height: 54px;\n"
"outline:none\n"
"")
        self.key21.setObjectName("key21")
        self.row1.addWidget(self.key21)
        self.key22 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key22.sizePolicy().hasHeightForWidth())
        self.key22.setSizePolicy(sizePolicy)
        self.key22.setStyleSheet("color: black;\n"
"background-color: rgb(204, 204, 204);\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"width: 54px;\n"
"height: 54px;\n"
"outline:none\n"
"")
        self.key22.setObjectName("key22")
        self.row1.addWidget(self.key22)
        self.key23 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key23.sizePolicy().hasHeightForWidth())
        self.key23.setSizePolicy(sizePolicy)
        self.key23.setStyleSheet("color: black;\n"
"background-color: rgb(204, 204, 204);\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"width: 54px;\n"
"height: 54px;\n"
"outline:none\n"
"")
        self.key23.setObjectName("key23")
        self.row1.addWidget(self.key23)
        self.key_layout.addLayout(self.row1, 3, 0, 1, 1)
        self.row2 = QtWidgets.QHBoxLayout()
        self.row2.setObjectName("row2")
        self.key24 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key24.sizePolicy().hasHeightForWidth())
        self.key24.setSizePolicy(sizePolicy)
        self.key24.setStyleSheet("color: black;\n"
"background-color: rgb(204, 204, 204);\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"width: 54px;\n"
"height: 54px;\n"
"outline:none\n"
"")
        self.key24.setObjectName("key24")
        self.row2.addWidget(self.key24)
        self.key25 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key25.sizePolicy().hasHeightForWidth())
        self.key25.setSizePolicy(sizePolicy)
        self.key25.setStyleSheet("color: black;\n"
"background-color: rgb(204, 204, 204);\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"width: 54px;\n"
"height: 54px;\n"
"outline:none\n"
"")
        self.key25.setObjectName("key25")
        self.row2.addWidget(self.key25)
        self.key26 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key26.sizePolicy().hasHeightForWidth())
        self.key26.setSizePolicy(sizePolicy)
        self.key26.setStyleSheet("color: black;\n"
"background-color: rgb(204, 204, 204);\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"width: 54px;\n"
"height: 54px;\n"
"outline:none\n"
"")
        self.key26.setObjectName("key26")
        self.row2.addWidget(self.key26)
        self.key27 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key27.sizePolicy().hasHeightForWidth())
        self.key27.setSizePolicy(sizePolicy)
        self.key27.setStyleSheet("color: black;\n"
"background-color: rgb(204, 204, 204);\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"width: 54px;\n"
"height: 54px;\n"
"outline:none\n"
"")
        self.key27.setObjectName("key27")
        self.row2.addWidget(self.key27)
        self.key28 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key28.sizePolicy().hasHeightForWidth())
        self.key28.setSizePolicy(sizePolicy)
        self.key28.setStyleSheet("color: black;\n"
"background-color: rgb(204, 204, 204);\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"width: 54px;\n"
"height: 54px;\n"
"outline:none\n"
"")
        self.key28.setObjectName("key28")
        self.row2.addWidget(self.key28)
        self.key29 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key29.sizePolicy().hasHeightForWidth())
        self.key29.setSizePolicy(sizePolicy)
        self.key29.setStyleSheet("color: black;\n"
"background-color: rgb(204, 204, 204);\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"width: 54px;\n"
"height: 54px;\n"
"outline:none\n"
"")
        self.key29.setObjectName("key29")
        self.row2.addWidget(self.key29)
        self.key30 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key30.sizePolicy().hasHeightForWidth())
        self.key30.setSizePolicy(sizePolicy)
        self.key30.setStyleSheet("color: black;\n"
"background-color: rgb(204, 204, 204);\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"width: 54px;\n"
"height: 54px;\n"
"outline:none\n"
"")
        self.key30.setObjectName("key30")
        self.row2.addWidget(self.key30)
        self.key31 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key31.sizePolicy().hasHeightForWidth())
        self.key31.setSizePolicy(sizePolicy)
        self.key31.setStyleSheet("color: black;\n"
"background-color: rgb(204, 204, 204);\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"width: 54px;\n"
"height: 54px;\n"
"outline:none\n"
"")
        self.key31.setObjectName("key31")
        self.row2.addWidget(self.key31)
        self.key32 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key32.sizePolicy().hasHeightForWidth())
        self.key32.setSizePolicy(sizePolicy)
        self.key32.setStyleSheet("color: black;\n"
"background-color: rgb(204, 204, 204);\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"width: 54px;\n"
"height: 54px;\n"
"outline:none\n"
"")
        self.key32.setObjectName("key32")
        self.row2.addWidget(self.key32)
        self.key33 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key33.sizePolicy().hasHeightForWidth())
        self.key33.setSizePolicy(sizePolicy)
        self.key33.setStyleSheet("color: black;\n"
"background-color: rgb(204, 204, 204);\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"width: 54px;\n"
"height: 54px;\n"
"outline:none\n"
"")
        self.key33.setObjectName("key33")
        self.row2.addWidget(self.key33)
        self.key34 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key34.sizePolicy().hasHeightForWidth())
        self.key34.setSizePolicy(sizePolicy)
        self.key34.setStyleSheet("color: black;\n"
"background-color: rgb(204, 204, 204);\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"width: 54px;\n"
"height: 54px;\n"
"outline:none\n"
"")
        self.key34.setObjectName("key34")
        self.row2.addWidget(self.key34)
        spacerItem2 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.row2.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.row2.addItem(spacerItem3)
        self.key_layout.addLayout(self.row2, 4, 0, 1, 1)
        self.row0 = QtWidgets.QHBoxLayout()
        self.row0.setObjectName("row0")
        spacerItem4 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.row0.addItem(spacerItem4)
        self.key0 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key0.sizePolicy().hasHeightForWidth())
        self.key0.setSizePolicy(sizePolicy)
        self.key0.setStyleSheet("color: black;\n"
"background-color: rgb(204, 204, 204);\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"width: 54px;\n"
"height: 54px;\n"
"outline:none\n"
"")
        self.key0.setProperty("key0", "")
        self.key0.setObjectName("key0")
        self.row0.addWidget(self.key0)
        self.key1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key1.sizePolicy().hasHeightForWidth())
        self.key1.setSizePolicy(sizePolicy)
        self.key1.setStyleSheet("color: black;\n"
"background-color: rgb(204, 204, 204);\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"width: 54px;\n"
"height: 54px;\n"
"outline:none\n"
"")
        self.key1.setProperty("key0", "")
        self.key1.setObjectName("key1")
        self.row0.addWidget(self.key1)
        self.key2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key2.sizePolicy().hasHeightForWidth())
        self.key2.setSizePolicy(sizePolicy)
        self.key2.setStyleSheet("color: black;\n"
"background-color: rgb(204, 204, 204);\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"width: 54px;\n"
"height: 54px;\n"
"outline:none\n"
"")
        self.key2.setProperty("key0", "")
        self.key2.setObjectName("key2")
        self.row0.addWidget(self.key2)
        self.key3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key3.sizePolicy().hasHeightForWidth())
        self.key3.setSizePolicy(sizePolicy)
        self.key3.setStyleSheet("color: black;\n"
"background-color: rgb(204, 204, 204);\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"width: 54px;\n"
"height: 54px;\n"
"outline:none\n"
"")
        self.key3.setProperty("key0", "")
        self.key3.setObjectName("key3")
        self.row0.addWidget(self.key3)
        self.key4 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key4.sizePolicy().hasHeightForWidth())
        self.key4.setSizePolicy(sizePolicy)
        self.key4.setStyleSheet("color: black;\n"
"background-color: rgb(204, 204, 204);\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"width: 54px;\n"
"height: 54px;\n"
"outline:none\n"
"")
        self.key4.setProperty("key0", "")
        self.key4.setObjectName("key4")
        self.row0.addWidget(self.key4)
        self.key5 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key5.sizePolicy().hasHeightForWidth())
        self.key5.setSizePolicy(sizePolicy)
        self.key5.setStyleSheet("color: black;\n"
"background-color: rgb(204, 204, 204);\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"width: 54px;\n"
"height: 54px;\n"
"outline:none\n"
"")
        self.key5.setProperty("key0", "")
        self.key5.setObjectName("key5")
        self.row0.addWidget(self.key5)
        self.key6 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key6.sizePolicy().hasHeightForWidth())
        self.key6.setSizePolicy(sizePolicy)
        self.key6.setStyleSheet("color: black;\n"
"background-color: rgb(204, 204, 204);\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"width: 54px;\n"
"height: 54px;\n"
"outline:none\n"
"")
        self.key6.setProperty("key0", "")
        self.key6.setObjectName("key6")
        self.row0.addWidget(self.key6)
        self.key7 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key7.sizePolicy().hasHeightForWidth())
        self.key7.setSizePolicy(sizePolicy)
        self.key7.setStyleSheet("color: black;\n"
"background-color: rgb(204, 204, 204);\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"width: 54px;\n"
"height: 54px;\n"
"outline:none\n"
"")
        self.key7.setProperty("key0", "")
        self.key7.setObjectName("key7")
        self.row0.addWidget(self.key7)
        self.key8 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key8.sizePolicy().hasHeightForWidth())
        self.key8.setSizePolicy(sizePolicy)
        self.key8.setStyleSheet("color: black;\n"
"background-color: rgb(204, 204, 204);\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"width: 54px;\n"
"height: 54px;\n"
"outline:none\n"
"")
        self.key8.setProperty("key0", "")
        self.key8.setObjectName("key8")
        self.row0.addWidget(self.key8)
        self.key9 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key9.sizePolicy().hasHeightForWidth())
        self.key9.setSizePolicy(sizePolicy)
        self.key9.setStyleSheet("color: black;\n"
"background-color: rgb(204, 204, 204);\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"width: 54px;\n"
"height: 54px;\n"
"outline:none\n"
"")
        self.key9.setProperty("key0", "")
        self.key9.setObjectName("key9")
        self.row0.addWidget(self.key9)
        self.key10 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key10.sizePolicy().hasHeightForWidth())
        self.key10.setSizePolicy(sizePolicy)
        self.key10.setStyleSheet("color: black;\n"
"background-color: rgb(204, 204, 204);\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"width: 54px;\n"
"height: 54px;\n"
"outline:none\n"
"")
        self.key10.setProperty("key0", "")
        self.key10.setObjectName("key10")
        self.row0.addWidget(self.key10)
        self.key11 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key11.sizePolicy().hasHeightForWidth())
        self.key11.setSizePolicy(sizePolicy)
        self.key11.setStyleSheet("color: black;\n"
"background-color: rgb(204, 204, 204);\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"width: 54px;\n"
"height: 54px;\n"
"outline:none\n"
"")
        self.key11.setProperty("key0", "")
        self.key11.setObjectName("key11")
        self.row0.addWidget(self.key11)
        spacerItem5 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.row0.addItem(spacerItem5)
        self.key_layout.addLayout(self.row0, 2, 0, 1, 1)
        self.main_vertical_layout.addLayout(self.key_layout)
        self.horizontalLayout_2.addLayout(self.main_vertical_layout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Project-e"))
        self.gen_label.setText(_translate("MainWindow", "current: 0"))
        self.gen_value_box.setPlaceholderText(_translate("MainWindow", "generation"))
        self.mingen_label.setText(_translate("MainWindow", "min: 0"))
        self.prog_start_btn.setText(_translate("MainWindow", "start"))
        self.prog_stop_btn.setText(_translate("MainWindow", "stop"))
        self.maxgen_label.setText(_translate("MainWindow", "max: 0"))
        self.lastgen_label.setText(_translate("MainWindow", "last: 0"))
        self.gencount_label.setText(_translate("MainWindow", "gen: 0"))
        self.prog_save_btn.setText(_translate("MainWindow", "save to file"))
        self.key12.setText(_translate("MainWindow", "a"))
        self.key13.setText(_translate("MainWindow", "s"))
        self.key14.setText(_translate("MainWindow", "d"))
        self.key15.setText(_translate("MainWindow", "f"))
        self.key16.setText(_translate("MainWindow", "g"))
        self.key17.setText(_translate("MainWindow", "h"))
        self.key18.setText(_translate("MainWindow", "j"))
        self.key19.setText(_translate("MainWindow", "k"))
        self.key20.setText(_translate("MainWindow", "l"))
        self.key21.setText(_translate("MainWindow", ";"))
        self.key22.setText(_translate("MainWindow", "\'"))
        self.key23.setText(_translate("MainWindow", "\\"))
        self.key24.setText(_translate("MainWindow", "<"))
        self.key25.setText(_translate("MainWindow", "z"))
        self.key26.setText(_translate("MainWindow", "x"))
        self.key27.setText(_translate("MainWindow", "c"))
        self.key28.setText(_translate("MainWindow", "v"))
        self.key29.setText(_translate("MainWindow", "b"))
        self.key30.setText(_translate("MainWindow", "n"))
        self.key31.setText(_translate("MainWindow", "m"))
        self.key32.setText(_translate("MainWindow", ","))
        self.key33.setText(_translate("MainWindow", "."))
        self.key34.setText(_translate("MainWindow", "/"))
        self.key0.setText(_translate("MainWindow", "q"))
        self.key1.setText(_translate("MainWindow", "w"))
        self.key2.setText(_translate("MainWindow", "e"))
        self.key3.setText(_translate("MainWindow", "r"))
        self.key4.setText(_translate("MainWindow", "t"))
        self.key5.setText(_translate("MainWindow", "y"))
        self.key6.setText(_translate("MainWindow", "u"))
        self.key7.setText(_translate("MainWindow", "i"))
        self.key8.setText(_translate("MainWindow", "o"))
        self.key9.setText(_translate("MainWindow", "p"))
        self.key10.setText(_translate("MainWindow", "["))
        self.key11.setText(_translate("MainWindow", "]"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
